name: ood-robustness
channels:
    - nvidia
    - pytorch
    - conda-forge
    - nodefaults
dependencies:
    - mamba>=1.0.0
    - conda-lock>=1.2.1
    - python>=3.11
    - cookiecutter>=2.1.1
    - pip>=22.2.20
    # Numpy and Pandas
    - numpy>=1.23.4
    - pandas>=1.5.1
    # Cuda
    - pytorch-cuda>=12.1
    - torchvision
    - torchaudio
    - opencv
    - wand # image manipulation library
    - pip:
          - python-dotenv>=0.21.0
          - pyprojroot>=0.2.0
          - nbdev>=2.3
          - rich # pritty printing
          - gdown # google donwloader
          # Hydra config
          - hydra-core
          - hydra_colorlog
          - hydra-submitit-launcher
          - hydra-joblib-launcher
          # Jupyter and extensions
          - jupyter
          - ipympl
          - nbdime>=3.1.1
          - ipywidgets
          # Plotting libraries
          - matplotlib>=3.6.2
          - seaborn>=0.12.1
          - plotly
          # Classic ML packages
          - scikit-learn>=1.1.3
          - scikit-image
          # Development dependencies
          - pre-commit>=2.12.0 # hooks for applying linters on commit
          - tox>=3.20.1 # test env management
          - tox-conda>=0.2.0 # test conda env management
          - pytest>=6.2.4 # code testing package
          - pytest_cov>=4.0.0 # test coverage
          - flake8>=5.0.4 # code analysis
          - isort>=5.10.1 # sort imports
          - black>=22.10.0 # code formatting
          - mypy>=0.982 # type checking
          # Project related
          - multiprocess # multiprocessing extension using 'dill'
          - torcheval # evaluation metric
          - timm # vision transformer
          - torch>=2.3.1+cu121
          - git+https://github.com/berni-lehner/zippee-ki-yay.git # model/dataset downloader
          - git+https://github.com/berni-lehner/hyperpyper.git # data pipeline utils
          # - git+https://github.com/berni-lehner/shapetastic.git # syntheic dataset generator
          - git+https://github.com/ml-jku/hopfield-boosting.git # hopfield boosting repo (use for training the models)
